// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: planner.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// PlannerServiceClient is the client API for PlannerService service.
type PlannerServiceClient interface {
	PlanMission(ctx context.Context, in *PlanMissionRequest, opts ...grpc.CallOption) (*PlanMissionResponse, error)
	ReassignZone(ctx context.Context, in *ReassignZoneRequest, opts ...grpc.CallOption) (*ReassignZoneResponse, error)
	DetectObjects(ctx context.Context, in *DetectObjectsRequest, opts ...grpc.CallOption) (*DetectObjectsResponse, error)
}

type plannerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlannerServiceClient(cc grpc.ClientConnInterface) PlannerServiceClient {
	return &plannerServiceClient{cc}
}

func (c *plannerServiceClient) PlanMission(ctx context.Context, in *PlanMissionRequest, opts ...grpc.CallOption) (*PlanMissionResponse, error) {
	out := new(PlanMissionResponse)
	err := c.cc.Invoke(ctx, "/planner.PlannerService/PlanMission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerServiceClient) ReassignZone(ctx context.Context, in *ReassignZoneRequest, opts ...grpc.CallOption) (*ReassignZoneResponse, error) {
	out := new(ReassignZoneResponse)
	err := c.cc.Invoke(ctx, "/planner.PlannerService/ReassignZone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plannerServiceClient) DetectObjects(ctx context.Context, in *DetectObjectsRequest, opts ...grpc.CallOption) (*DetectObjectsResponse, error) {
	out := new(DetectObjectsResponse)
	err := c.cc.Invoke(ctx, "/planner.PlannerService/DetectObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlannerServiceServer is the server API for PlannerService service.
type PlannerServiceServer interface {
	PlanMission(context.Context, *PlanMissionRequest) (*PlanMissionResponse, error)
	ReassignZone(context.Context, *ReassignZoneRequest) (*ReassignZoneResponse, error)
	DetectObjects(context.Context, *DetectObjectsRequest) (*DetectObjectsResponse, error)
	mustEmbedUnimplementedPlannerServiceServer()
}

// UnimplementedPlannerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPlannerServiceServer struct{}

func (UnimplementedPlannerServiceServer) PlanMission(context.Context, *PlanMissionRequest) (*PlanMissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanMission not implemented")
}

func (UnimplementedPlannerServiceServer) ReassignZone(context.Context, *ReassignZoneRequest) (*ReassignZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReassignZone not implemented")
}

func (UnimplementedPlannerServiceServer) DetectObjects(context.Context, *DetectObjectsRequest) (*DetectObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectObjects not implemented")
}

func (UnimplementedPlannerServiceServer) mustEmbedUnimplementedPlannerServiceServer() {}

// UnsafePlannerServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafePlannerServiceServer interface {
	mustEmbedUnimplementedPlannerServiceServer()
}

func RegisterPlannerServiceServer(s grpc.ServiceRegistrar, srv PlannerServiceServer) {
	s.RegisterService(&PlannerService_ServiceDesc, srv)
}

func _PlannerService_PlanMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).PlanMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planner.PlannerService/PlanMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).PlanMission(ctx, req.(*PlanMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlannerService_ReassignZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).ReassignZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planner.PlannerService/ReassignZone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).ReassignZone(ctx, req.(*ReassignZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlannerService_DetectObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlannerServiceServer).DetectObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/planner.PlannerService/DetectObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlannerServiceServer).DetectObjects(ctx, req.(*DetectObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlannerService_ServiceDesc is the grpc.ServiceDesc for PlannerService service.
var PlannerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "planner.PlannerService",
	HandlerType: (*PlannerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanMission",
			Handler:    _PlannerService_PlanMission_Handler,
		},
		{
			MethodName: "ReassignZone",
			Handler:    _PlannerService_ReassignZone_Handler,
		},
		{
			MethodName: "DetectObjects",
			Handler:    _PlannerService_DetectObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "planner.proto",
}
