// Code generated by protoc-gen-go. DO NOT EDIT.
// source: planner.proto

package proto

// LatLng is a GPS coordinate pair.
type LatLng struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

// Waypoint is a 3D GPS coordinate.
type Waypoint struct {
	Lat  float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng  float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	AltM float64 `protobuf:"fixed64,3,opt,name=alt_m,json=altM,proto3" json:"alt_m,omitempty"`
}

// DroneInfo carries basic drone metadata for planner requests.
type DroneInfo struct {
	DroneId string  `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat     float64 `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng     float64 `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Battery int32   `protobuf:"varint,5,opt,name=battery,proto3" json:"battery,omitempty"`
}

// ZoneAssignment maps a drone to a sub-zone with waypoints.
type ZoneAssignment struct {
	ZoneId     string      `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	DroneId    string      `protobuf:"bytes,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Waypoints  []*Waypoint `protobuf:"bytes,3,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	SubPolygon []*LatLng   `protobuf:"bytes,4,rep,name=sub_polygon,json=subPolygon,proto3" json:"sub_polygon,omitempty"`
}

// PlanMissionRequest is sent by the Go gateway to request mission planning.
type PlanMissionRequest struct {
	MissionId   string       `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	ZonePolygon []*LatLng    `protobuf:"bytes,2,rep,name=zone_polygon,json=zonePolygon,proto3" json:"zone_polygon,omitempty"`
	Drones      []*DroneInfo `protobuf:"bytes,3,rep,name=drones,proto3" json:"drones,omitempty"`
	AltitudeM   float64      `protobuf:"fixed64,4,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`
	AirspeedMs  float64      `protobuf:"fixed64,5,opt,name=airspeed_ms,json=airspeedMs,proto3" json:"airspeed_ms,omitempty"`
	StripWidthM float64      `protobuf:"fixed64,6,opt,name=strip_width_m,json=stripWidthM,proto3" json:"strip_width_m,omitempty"`
}

// PlanMissionResponse is returned by the Python planner after zone decomposition.
type PlanMissionResponse struct {
	MissionId string            `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	Zones     []*ZoneAssignment `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	Status    string            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error     string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

// ReassignZoneRequest is sent when a drone faults mid-mission.
type ReassignZoneRequest struct {
	MissionId       string       `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	FaultedDroneId  string       `protobuf:"bytes,2,opt,name=faulted_drone_id,json=faultedDroneId,proto3" json:"faulted_drone_id,omitempty"`
	FaultedZoneId   string       `protobuf:"bytes,3,opt,name=faulted_zone_id,json=faultedZoneId,proto3" json:"faulted_zone_id,omitempty"`
	AvailableDrones []*DroneInfo `protobuf:"bytes,4,rep,name=available_drones,json=availableDrones,proto3" json:"available_drones,omitempty"`
	AltitudeM       float64      `protobuf:"fixed64,5,opt,name=altitude_m,json=altitudeM,proto3" json:"altitude_m,omitempty"`
	AirspeedMs      float64      `protobuf:"fixed64,6,opt,name=airspeed_ms,json=airspeedMs,proto3" json:"airspeed_ms,omitempty"`
	StripWidthM     float64      `protobuf:"fixed64,7,opt,name=strip_width_m,json=stripWidthM,proto3" json:"strip_width_m,omitempty"`
}

// ReassignZoneResponse is returned after zone reassignment.
type ReassignZoneResponse struct {
	ReplacementDroneId string            `protobuf:"bytes,1,opt,name=replacement_drone_id,json=replacementDroneId,proto3" json:"replacement_drone_id,omitempty"`
	NewZones           []*ZoneAssignment `protobuf:"bytes,2,rep,name=new_zones,json=newZones,proto3" json:"new_zones,omitempty"`
	Status             string            `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error              string            `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

// DetectObjectsRequest carries a JPEG frame for YOLOv8 inference.
type DetectObjectsRequest struct {
	DroneId     string `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	MissionId   string `protobuf:"bytes,2,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	FrameJpeg   []byte `protobuf:"bytes,3,opt,name=frame_jpeg,json=frameJpeg,proto3" json:"frame_jpeg,omitempty"`
	FrameWidth  int32  `protobuf:"varint,4,opt,name=frame_width,json=frameWidth,proto3" json:"frame_width,omitempty"`
	FrameHeight int32  `protobuf:"varint,5,opt,name=frame_height,json=frameHeight,proto3" json:"frame_height,omitempty"`
}

// Detection is a single YOLOv8 bounding box result.
type Detection struct {
	Label      string  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	X1         float32 `protobuf:"fixed32,3,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1         float32 `protobuf:"fixed32,4,opt,name=y1,proto3" json:"y1,omitempty"`
	X2         float32 `protobuf:"fixed32,5,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2         float32 `protobuf:"fixed32,6,opt,name=y2,proto3" json:"y2,omitempty"`
}

// DetectObjectsResponse contains all detections for a single frame.
type DetectObjectsResponse struct {
	DroneId     string       `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Detections  []*Detection `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`
	TimestampMs int64        `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
}
