# This file is generated from gateway/proto/planner.proto
# Run the following command from the planner/ directory to regenerate:
#
#   pip install grpcio-tools
#   python -m grpc_tools.protoc \
#       -I../gateway/proto \
#       --python_out=./proto \
#       --grpc_python_out=./proto \
#       planner.proto
#
# DO NOT edit this file manually.
# This stub exists so the project tree is complete before Phase 5 generation.

raise ImportError(
    "planner_pb2 has not been generated yet. "
    "Run: python -m grpc_tools.protoc -I../gateway/proto "
    "--python_out=./proto --grpc_python_out=./proto planner.proto"
)